### ISSUE TITLE
Not actually a syslog handler

### ISSUE THREAD

**Issue by lpar** [samber/slog-syslog#2]
I was hoping this would be a handler to write syslog messages to syslog (RFC5424), but on testing it isn't, it dumps unmarked JSON into syslogd. (Not even [CEE tagged](https://sematext.com/blog/structured-logging-with-rsyslog-and-elasticsearch/).)

It might be good to note this at the top of the README.

**Comment by samber** [comment]
I just made a fix. 

It should work now.
