### ISSUE TITLE
WithGroup methos returns new handler instead of receiver

### ISSUE THREAD

**Issue by katevi** [samber/slog-syslog#4]
Hi! 
It looks like syslog handler always returns new handler even when name is empty: https://github.com/samber/slog-syslog/blob/main/handler.go#L103 .

Though golang docs https://pkg.go.dev/log/slog#Handler says:

> // If the name is empty, WithGroup returns the receiver.

is it ok?

**Comment by samber** [comment]
I agree. Could you please suggest a fix ?

**Comment by katevi** [comment]
ok I'll do that =)
